export default function Head() {
  return (
    <>
      <title>Neo | Home</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/eyeglasses.png" style={{ width: "auto", height: "auto" }} />
    </>
  )
}
